# This Compose file deploys the latest version of the Splunk OpenTelemetry Collector.
#
# There are two major things to change here:
#
# 1. The `hostname` of the container
# - Change it to the name of the host you want to see in the O11y UI
#
# 2. The OTel Collector Config
# - There are two options, use the default *agent* config, or use the "custom" *agent* config
# - Change it via `environment` variable SPLUNK_CONFIG
#
#   - The default config works except that it doesn't define `deployment.environment`, which
#     is a nice way to tag entities in O11y Cloud.  But for a quick test, it's fine.
#
#   - The cusom config will apply the `deployment.environment` resource attribute to all
#     telemetry signals, and so is recommended.  Be sure to follow the instructions at the
#     top of the `otel-collector-config.yaml` file to adjust per your environment.
#     NOTE: the UI is wonky with environment, though, I can't seem to consistently use it...
services:

  # Splunk OTel Collector
  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    restart: always
    container_name: splunk-otel-collector
    #hostname: kjt-plain-old-docker-container-10-11-2024
    volumes:
      - type: bind
        source: ./custom-otel-collector-config.yaml
        target: /etc/otel/collector/custom-otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55670:55679" # zpages extension
      - "55680:55680" # alternate gRPC receiver
      - "55681:55681" # http
      - "14250:14250" # unknown reason, but listed in docs
      - "14268:14268" # unknown reason, but listed in docs
      - "6060:6060"   # unknown reason, but listed in docs
      - "7276:7276"   # unknown reason, but listed in docs
      - "9080:9080"   # unknown reason, but listed in docs
      - "9411:9411"   # unknown reason, but listed in docs
      - "9943:9943"   # unknown reason, but listed in docs
    environment:
      # Variables are defined in `.env` file
      # Provide ingest access token
      SPLUNK_ACCESS_TOKEN: ${SPLUNK_ACCESS_TOKEN}
      # Choose realm
      SPLUNK_REALM: ${SPLUNK_REALM}
      # You must supply *either* the default or the custom config, because if not, the collector will run in gateway mode, and won't monitor the host
      # Default
      SPLUNK_CONFIG: /etc/otel/collector/agent_config.yaml
      # Custom
      # SPLUNK_CONFIG: /etc/otel/collector/custom-otel-collector-config.yaml